import { applyCharm } from '@/lib/pricing/local/psychological';
import { formatPrice, flag } from '@/lib/fairpricing/workspace';
const examples=[
 {code:'US',name:'United States',currency:'USD',amount:10.42,note:'A familiar .99 ending'},
 {code:'IN',name:'India',currency:'INR',amount:412.60,note:'Whole rupees ending in 9'},
 {code:'JP',name:'Japan',currency:'JPY',amount:1183,note:'Round amounts in whole yen'},
 {code:'SN',name:'Senegal',currency:'XOF',amount:2470,note:'Rounded to a multiple of 100'},
];
export function PsychologicalPricing(){
 return <section className="border-b bg-muted/20"><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-2"><div><p className="mb-4 text-sm font-medium uppercase tracking-widest text-primary">Psychological pricing</p><h2 className="text-3xl font-semibold tracking-tight">Local prices. Local endings.</h2><p className="mt-5 leading-relaxed text-muted-foreground">Currency conversion can leave you with an awkward price. Smart local endings suggest amounts suited to each market, from whole rupees ending in 9 to round yen and CFA franc amounts.</p><p className="mt-4 leading-relaxed text-muted-foreground">You choose whether to use these conventions. Your price bounds still apply, and Apple prices must fit the available store price points. The examples show rounding only, before store-specific validation.</p></div><div className="grid overflow-hidden rounded-xl border bg-card sm:grid-cols-2">{examples.map(e=>{const result=applyCharm(e.amount,e.code,e.currency,{ending:'.99',smartLocaleDefaults:true});return <div key={e.code} className="border-b p-6 odd:sm:border-r last:border-b-0 sm:[&:nth-last-child(2)]:border-b-0"><p className="text-sm text-muted-foreground">{flag(e.code)} {e.name}</p><div className="my-4 flex flex-wrap items-center gap-3 tabular-nums"><span className="text-lg text-muted-foreground line-through">{formatPrice(e.amount,e.currency)}</span><span aria-label="becomes" className="text-muted-foreground">→</span><strong className="text-2xl font-semibold text-primary">{formatPrice(result.price,e.currency)}</strong></div><p className="text-sm text-muted-foreground">{e.note}</p></div>})}</div></div></section>;
}
