import Link from 'next/link';
import { PsychologicalPricing } from '@/components/landing/psychological-pricing';
import { LandingNav } from '@/components/landing/landing-nav';
import { LandingFooter } from '@/components/landing/landing-footer';
import { ConversionTableDemo } from '@/components/landing/conversion-table-demo';

export default function Home() {
  return <div className="landing-page min-h-screen bg-background">
    <LandingNav />
    <main>
      <section className="mx-auto max-w-7xl px-5 py-12 md:py-20">
        <div className="grid items-start gap-12 lg:grid-cols-2">
          <div className="space-y-8 lg:pt-6">
            <div className="space-y-5"><h1 className="text-4xl font-semibold tracking-tight md:text-5xl leading-tight">Regional pricing for the App Store and Google Play</h1><p className="max-w-lg text-lg leading-relaxed text-muted-foreground">Compare currency conversion with purchasing power, Big Mac, Netflix, and GDP indexes. Choose a strategy, review local prices, and apply them to your store products.</p></div>
            <ol className="space-y-5">{[['Connect your store','Connect Google Play or App Store Connect, then choose your app. Each store has its own connection.'],['Review regional prices','Your products and subscriptions load from the selected app. Choose an index, rounding, and countries to update.'],['Apply your changes','Review the proposed prices and confirm before sending changes to the store.']].map(([title,text],i)=><li key={title} className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-muted text-sm">{i+1}</span><div><h2 className="font-medium">{title}</h2><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{text}</p></div></li>)}</ol>
            <Link href="/setup" className="inline-flex h-11 items-center rounded-md bg-primary px-6 font-medium text-primary-foreground">Connect your store</Link>
            <p className="text-sm text-muted-foreground">Free to use. Try the calculator without connecting an account.</p>
          </div>
          <ConversionTableDemo />
        </div>
      </section>
      <section className="border-t"><div className="mx-auto max-w-7xl px-5 py-16 md:py-20"><div className="mb-8 max-w-2xl"><p className="mb-3 text-sm font-medium text-primary">Pricing strategies</p><h2 className="text-3xl font-semibold tracking-tight">Choose a reference for your prices</h2><p className="mt-4 leading-relaxed text-muted-foreground">Use one index or combine several. The calculator and connected editors use the same pricing strategies.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['World Bank PPP','Adjust prices using relative purchasing power.'],['Big Mac Index','Compare the local cost of an everyday purchase.'],['Netflix Index','Use regional digital subscription prices as a reference.'],['GDP-adjusted','Scale prices using nominal GDP per person.'],['Exchange rate','Convert the base price without an affordability adjustment.'],['Custom blend','Combine indexes with your own percentage weights.']].map(([title,text])=><div key={title} className="rounded-xl border bg-card p-6"><h3 className="font-medium">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></div>)}</div><p className="mt-8 text-sm text-muted-foreground">Reference data includes dated snapshots and estimates where observations are missing. Results are pricing suggestions, not guaranteed revenue improvements.</p></div></section>
      <PsychologicalPricing/>
      <section id="faq" className="border-t scroll-mt-16"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:py-20 lg:grid-cols-[1fr_1.4fr]"><div><p className="mb-3 text-sm font-medium text-primary">Using FairPricing</p><h2 className="text-3xl font-semibold tracking-tight">Frequently asked questions</h2><p className="mt-4 max-w-md leading-relaxed text-muted-foreground">How the calculator, store connections, and price updates work.</p><Link href="/setup-guide" className="mt-5 inline-block text-sm font-medium underline underline-offset-4">Read the store setup guide</Link></div><div className="overflow-hidden rounded-xl border bg-card">{[
        ['What can I do before connecting a store?','Enter a USD base price, compare all six pricing strategies, choose price endings, and preview country prices in the table or map. You can also enable the US price cap and smart local endings. This calculator uses bundled data; it does not load or update your store products.'],
        ['Which pricing strategies are available?','World Bank purchasing power parity (PPP), Big Mac Index, Netflix Index, GDP-adjusted pricing, exchange-rate conversion, and a custom weighted blend. Blend weights must total 100%. These are reference models, not predictions of sales or revenue.'],
        ['What does “Never price above United States” do?','In the landing calculator, it limits each country’s final price to the currency-converted value of your US base price, including after rounding. In connected editors the cap follows your selected base country. Conflicting minimum prices are flagged, and Apple price-point resolution respects the ceiling.'],
        ['How do smart local endings differ from .99 rounding?','A fixed ending applies your chosen rounding rule. Smart local endings add optional market conventions, such as whole rupees ending in 9, round yen, and CFA franc amounts in multiples of 100. Price bounds take priority, and Apple’s available tiers can change an ending. Choosing Off disables psychological rounding.'],
        ['What does the map show?','Country colors show calculated prices relative to straight currency conversion. Hover, tap, or focus a country to see its price. Gray countries have no available price in the preview. Small territories may only appear in the table.'],
        ['What happens when I connect a store?','The dashboard loads products and subscriptions for your selected app. Connect Google Play and App Store Connect separately, then switch between them in the dashboard. Products are not merged across stores, and no sample product is added to your account.'],
        ['Does changing a strategy publish prices immediately?','No. In the bulk editor, select the countries, review the proposed prices, and confirm Apply before updates are sent through the store API. The landing calculator never publishes. Check the result for skipped territories or errors; not every regional update is guaranteed to succeed.'],
        ['Are the exchange rates and indexes live?','The landing calculator uses dated snapshots and explicitly defined estimates where observations are missing. Connected workflows can use fetched PPP data and live exchange rates when an Open Exchange Rates key is configured. They can fall back to bundled data. See Source, data & privacy for sources and dates.'],
        ['Where do my API credentials go?','They are sent to this deployment’s server to authenticate with Apple or Google. Sessions are encrypted in HTTP-only cookies; private keys are not written to an application database or sent to pricing-kit.com. If you self-host, you control the code and encryption key, but your hosting provider still runs the server.'],
        ['Will updates affect existing subscribers?','That depends on the store and subscription settings. Review the price-preservation and scheduling options in the connected editor before confirming a change. FairPricing does not promise that every price update leaves existing subscribers unaffected.'],
        ['Is FairPricing free and self-hostable?','Yes. FairPricing has no paid plans or billing integration. Its source is available under GPLv3, and you can run it on your own infrastructure. Hosting and any optional data-provider usage remain your responsibility.']
      ].map(([title,text])=><details key={title} className="group border-b last:border-b-0"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 px-6 py-5 text-sm font-medium [&::-webkit-details-marker]:hidden">{title}<span aria-hidden="true" className="text-lg text-muted-foreground group-open:rotate-45">+</span></summary><p className="px-6 pb-6 text-sm leading-relaxed text-muted-foreground">{text}</p></details>)}</div></div></section>
    </main><LandingFooter />
  </div>;
}
