'use client';
import { useState } from 'react';
import { Search, ArrowUpDown, Pencil, LockKeyhole, RotateCcw, AlertCircle } from 'lucide-react';
import { flag, formatPrice, type PriceRow } from '@/lib/fairpricing/workspace';

export function CountryTable({rows, currency, onEdit, selected, setSelected, onReset}: {rows: PriceRow[]; currency: string; onEdit: (row: PriceRow) => void; selected: string[]; setSelected: (codes: string[]) => void; onReset: () => void}) {
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const [sort, setSort] = useState<'name' | 'change'>('name');
  const [page, setPage] = useState(0);
  const matching = rows.filter(r => `${r.name} ${r.code} ${r.currency}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || filter === 'overrides' && r.isOverride || filter === 'errors' && r.error)).sort((a, b) => sort === 'change' ? a.change - b.change : a.name.localeCompare(b.name));
  const pageCount = Math.max(1, Math.ceil(matching.length / 12));
  const safePage = Math.min(page, pageCount - 1);
  const visible = matching.slice(safePage * 12, safePage * 12 + 12);
  const allSelected = visible.length > 0 && visible.every(r => selected.includes(r.code));
  return <section className="fair-panel fair-country-panel"><div className="fair-table-heading"><div><h2>Country prices</h2><p>Compare calculated prices or edit a country.</p></div><span className="fair-pill">{rows.length} markets</span></div>
    <div className="fair-table-tools"><label className="fair-search"><Search size={16}/><input aria-label="Search countries" placeholder="Search country or currency…" value={search} onChange={e => {setSearch(e.target.value); setPage(0);}}/></label><select aria-label="Filter markets" value={filter} onChange={e => {setFilter(e.target.value); setPage(0);}}><option value="all">All markets</option><option value="overrides">Manual overrides</option><option value="errors">Needs attention</option></select>{selected.length > 0 && <button className="fair-button fair-secondary" onClick={onReset}><RotateCcw size={13}/> Reset {selected.length} selected</button>}</div>
    <div className="fair-table-scroll"><table className="fair-country-table"><thead><tr><th className="fair-check"><input aria-label="Select visible countries" type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? selected.filter(c => !visible.some(r => r.code === c)) : [...new Set([...selected, ...visible.map(r => r.code)])])}/></th><th><button onClick={() => setSort('name')}>Country <ArrowUpDown size={11}/></button></th><th>FX price</th><th>Fair price</th><th>In {currency}</th><th><button onClick={() => setSort('change')}>vs. FX <ArrowUpDown size={11}/></button></th><th>Data source</th><th><span className="sr-only">Edit</span></th></tr></thead><tbody>{visible.map(r => <tr key={r.code}><td className="fair-check"><input aria-label={`Select ${r.name}`} type="checkbox" checked={selected.includes(r.code)} onChange={() => setSelected(selected.includes(r.code) ? selected.filter(c => c !== r.code) : [...selected, r.code])}/></td><td><div className="fair-country-name"><span className="fair-flag" aria-hidden="true">{flag(r.code)}</span><div><strong>{r.name}</strong><small>{r.currency} <span>· {r.code}</span></small></div></div></td><td className="fair-fx">{Number.isFinite(r.fxPrice) ? formatPrice(r.fxPrice, r.currency) : 'Unavailable'}</td><td className="fair-final-price">{r.error ? <span className="fair-error-text" title={r.error}><AlertCircle size={13}/> Review</span> : <>{formatPrice(r.price, r.currency)}{r.isOverride && <LockKeyhole size={11} aria-label="Manual override"/>}</>}</td><td>{r.error ? '—' : formatPrice(r.baseEquivalent, currency)}</td><td>{r.error ? '—' : <span className={`fair-change ${r.change > 0 ? 'higher' : ''}`}>{r.change > 0 ? '+' : ''}{r.change.toFixed(0)}%</span>}</td><td><span className="fair-source">{r.isOverride ? 'Manual override' : r.source}</span></td><td><button className="fair-icon-button" aria-label={`Edit ${r.name} price`} onClick={() => onEdit(r)}><Pencil size={14}/></button></td></tr>)}</tbody></table></div>
    {visible.length === 0 && <div className="fair-empty"><Search size={25}/><h3>No markets found</h3><p>Try another country or clear your filters.</p><button onClick={() => {setSearch(''); setFilter('all');}}>Clear filters</button></div>}
    <div className="fair-table-footer"><span>{matching.length ? `${safePage * 12 + 1}–${Math.min((safePage + 1) * 12, matching.length)} of ${matching.length} markets` : '0 markets'}</span><div><button disabled={safePage === 0} onClick={() => setPage(safePage - 1)}>Previous</button><span>{safePage + 1} / {pageCount}</span><button disabled={safePage + 1 >= pageCount} onClick={() => setPage(safePage + 1)}>Next</button></div></div>
  </section>;
}
